version: 1.0.{build}

nuget:

  account_feed: true

  project_feed: true

notifications:

- provider: Email

  to:

  - zuha@zwsite.onmicrosoft.com

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: false
