version: 1.0.{build}

nuget:

  account_feed: true

  project_feed: true

build:

  publish_nuget: true

  publish_nuget_symbols: true

  use_snupkg_format: true

  include_nuget_references: true

  verbosity: minimal

notifications:

- provider: Email

  to:

  - zuha@zwsite.onmicrosoft.com

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: false
